[package]
name = "nvfancontrol"
version = "0.2.0"
authors = ["Spyros Stathopoulos <spystath@gmail.com>"]

[dependencies]
log = "*"
getopts = "*"
time = "*"

[target.'cfg(unix)'.dependencies]
xdg = "2.0.0-pre7"
nix = "*"

[target.'cfg(windows)'.dependencies]
ctrlc = "*"

[dependencies.nvctrl]
path = "src/nvctrl"

