[package]
name = "nvfancontrol"
version = "0.4.99"
authors = ["Spyros Stathopoulos <spystath@gmail.com>"]

[dependencies]
log = "0.4"
getopts = "*"
time = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
dirs = "*"

[target.'cfg(unix)'.dependencies]
nix = "*"

[target.'cfg(windows)'.dependencies]
ctrlc = "*"

[dependencies.nvctrl]
path = "src/nvctrl"

[features]
dynamic-xnvctrl = ["nvctrl/dynamic-xnvctrl"]
