[package]
name = "nvctrl"
version = "0.3.0"
authors = ["Spyros Stathopoulos <spystath@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "*"
serde = "*"
serde_derive = "*"

[target.'cfg(windows)'.dependencies]
libloading = "*"
lazy_static = "*"

[lib]
name = "nvctrl"
path = "lib.rs"

[features]
dynamic-xnvctrl = []
